export type ITodo = {
  title: string;
  date: Date;
};

export const d = [
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
  { name: "dd" },
];
